# Generated by Django 5.2.15 on 2026-06-24 03:57

import django.core.validators
import django.db.models.deletion
import tienda.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del carrito')),
                ('actualizado', models.DateTimeField(auto_now=True, help_text='Última actualización del carrito')),
                ('usuario', models.OneToOneField(help_text='Usuario propietario del carrito', on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100, unique=True, validators=[tienda.models.validate_no_special_chars])),
                ('slug', models.SlugField(blank=True, help_text='URL amigable para la categoría', unique=True, validators=[tienda.models.validate_slug])),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría', null=True)),
                ('icono', models.CharField(blank=True, help_text='Clase de Font Awesome (ej: fa-tshirt)', max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to='categorias/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
                ('es_activa', models.BooleanField(default=True, help_text='Indica si la categoría está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['slug'], name='tienda_cate_slug_b1a132_idx'), models.Index(fields=['es_activa'], name='tienda_cate_es_acti_516792_idx')],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=200, validators=[tienda.models.validate_no_special_chars])),
                ('slug', models.SlugField(blank=True, help_text='URL amigable para el producto', unique=True, validators=[tienda.models.validate_slug])),
                ('subcategoria', models.CharField(blank=True, help_text='Subcategoría del producto', max_length=100, validators=[tienda.models.validate_no_special_chars])),
                ('precio', models.DecimalField(decimal_places=0, help_text='Precio del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=0, help_text='Precio en oferta (si aplica)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('descripcion', models.TextField(help_text='Descripción detallada del producto')),
                ('caracteristicas', models.JSONField(blank=True, default=list, help_text='Lista de características del producto')),
                ('tallas', models.JSONField(default=list, help_text='Lista de tallas disponibles (ej: ["S", "M", "L"])', validators=[tienda.models.validate_tallas])),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario')),
                ('stock_minimo', models.PositiveIntegerField(default=5, help_text='Stock mínimo para alerta')),
                ('imagen_principal', models.ImageField(blank=True, help_text='Imagen principal del producto', null=True, upload_to='productos/')),
                ('imagenes', models.JSONField(blank=True, default=list, help_text='Lista de URLs de imágenes adicionales')),
                ('rating', models.FloatField(default=0, help_text='Calificación promedio del producto (0-5)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('reseñas', models.PositiveIntegerField(default=0, help_text='Número total de reseñas')),
                ('es_destacado', models.BooleanField(default=False, help_text='Indica si el producto está destacado')),
                ('es_nuevo', models.BooleanField(default=False, help_text='Indica si el producto es nuevo')),
                ('esta_activo', models.BooleanField(default=True, help_text='Indica si el producto está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('categoria', models.ForeignKey(help_text='Categoría del producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se agregó a favoritos')),
                ('usuario', models.ForeignKey(help_text='Usuario que marcó el favorito', on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(help_text='Producto marcado como favorito', on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'ordering': ['-agregado'],
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(help_text='Talla seleccionada del producto', max_length=5)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad del producto', validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se agregó al carrito')),
                ('carrito', models.ForeignKey(help_text='Carrito al que pertenece el item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tienda.carrito')),
                ('producto', models.ForeignKey(help_text='Producto en el carrito', on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
            options={
                'verbose_name': 'Item del Carrito',
                'verbose_name_plural': 'Items del Carrito',
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['slug'], name='tienda_prod_slug_646ce0_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'esta_activo'], name='tienda_prod_categor_baec14_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['es_destacado'], name='tienda_prod_es_dest_4b14c1_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['es_nuevo'], name='tienda_prod_es_nuev_843495_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['-rating'], name='tienda_prod_rating_17e9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='favorito',
            index=models.Index(fields=['usuario', 'producto'], name='tienda_favo_usuario_4c59bd_idx'),
        ),
        migrations.AddIndex(
            model_name='favorito',
            index=models.Index(fields=['-agregado'], name='tienda_favo_agregad_aeb633_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'producto')},
        ),
        migrations.AddIndex(
            model_name='carritoitem',
            index=models.Index(fields=['carrito', 'producto'], name='tienda_carr_carrito_2ee71a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together={('carrito', 'producto', 'talla')},
        ),
    ]
