# Generated by Django 5.2.15 on 2026-06-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenes',
            field=models.JSONField(default=list, help_text='Lista de URLs de imágenes adicionales'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tallas',
            field=models.JSONField(default=list, help_text='Lista de tallas disponibles'),
        ),
    ]
