# Generated by Django 5.2.15 on 2026-06-24 03:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('user', 'Usuario Regular')], default='user', help_text='Rol del usuario en el sistema', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[website.models.validate_phone_number])),
                ('direccion', models.TextField(blank=True, help_text='Dirección de residencia o envío', null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del usuario', null=True)),
                ('ultimo_cambio_password', models.DateTimeField(blank=True, help_text='Última vez que se cambió la contraseña', null=True)),
                ('intentos_fallidos', models.PositiveIntegerField(default=0, help_text='Número de intentos de login fallidos')),
                ('bloqueado_hasta', models.DateTimeField(blank=True, help_text='Fecha hasta que el usuario está bloqueado', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActividadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('creacion', 'Creación de Registro'), ('edicion', 'Edición de Registro'), ('eliminacion', 'Eliminación de Registro'), ('compra', 'Compra Realizada'), ('error', 'Error del Sistema'), ('seguridad', 'Evento de Seguridad')], max_length=20)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la actividad')),
                ('ip', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde la que se realizó la actividad', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User Agent del navegador', null=True)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la actividad')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de Usuario',
                'verbose_name_plural': 'Actividades de Usuarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Biografía o descripción del usuario', max_length=500, null=True)),
                ('avatar', models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='avatars/')),
                ('preferencias', models.JSONField(blank=True, default=dict, help_text='Preferencias del usuario (JSON)')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización del perfil')),
                ('usuario', models.OneToOneField(help_text='Usuario asociado a este perfil', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('first_name', models.CharField(help_text='Nombre del cliente', max_length=50, validators=[website.models.validate_no_special_chars])),
                ('last_name', models.CharField(help_text='Apellido del cliente', max_length=50, validators=[website.models.validate_no_special_chars])),
                ('email', models.EmailField(help_text='Correo electrónico del cliente', max_length=100, validators=[website.models.validate_email])),
                ('phone', models.CharField(help_text='Número de teléfono del cliente', max_length=15, validators=[website.models.validate_phone_number])),
                ('address', models.CharField(help_text='Dirección del cliente', max_length=100)),
                ('city', models.CharField(help_text='Ciudad del cliente', max_length=50, validators=[website.models.validate_no_special_chars])),
                ('state', models.CharField(help_text='Departamento/Estado del cliente', max_length=50, validators=[website.models.validate_no_special_chars])),
                ('zip_code', models.CharField(help_text='Código postal', max_length=10, validators=[website.models.validate_zip_code])),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el registro está activo')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el cliente', null=True)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_updated', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que creó o gestiona este registro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Cliente',
                'verbose_name_plural': 'Registros de Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['username'], name='website_usu_usernam_1d40a0_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='website_usu_email_54d481_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='website_usu_rol_1f9b09_idx'),
        ),
        migrations.AddIndex(
            model_name='actividadusuario',
            index=models.Index(fields=['-fecha'], name='website_act_fecha_b04939_idx'),
        ),
        migrations.AddIndex(
            model_name='actividadusuario',
            index=models.Index(fields=['usuario', 'tipo'], name='website_act_usuario_a28fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['email'], name='website_rec_email_1475a1_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['first_name', 'last_name'], name='website_rec_first_n_573282_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['-created_at'], name='website_rec_created_0aeff7_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['is_active'], name='website_rec_is_acti_f6a8d0_idx'),
        ),
    ]
