# Generated by Django 5.2.15 on 2026-06-25 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(help_text='Número de identificación único del cliente', max_length=20, unique=True, verbose_name='Identificación')),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido del cliente', max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del cliente (opcional)', max_length=200, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del cliente (opcional)', max_length=20, null=True, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, help_text='Dirección del cliente (opcional)', null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad del cliente (opcional)', max_length=100, null=True, verbose_name='Ciudad')),
                ('tipo_cliente', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('corporativo', 'Corporativo'), ('distribuidor', 'Distribuidor')], default='regular', help_text='Tipo de cliente (Regular, VIP, Corporativo, Distribuidor)', max_length=20, verbose_name='Tipo de Cliente')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cliente está activo', verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que actualizó el cliente por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_actualizados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que gestiona este cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['identificacion'], name='clientes_cl_identif_add71b_idx'), models.Index(fields=['email'], name='clientes_cl_email_eae461_idx'), models.Index(fields=['tipo_cliente'], name='clientes_cl_tipo_cl_cae2d6_idx'), models.Index(fields=['activo'], name='clientes_cl_activo_b76065_idx')],
            },
        ),
    ]
