# Generated by Django 5.2.15 on 2026-06-24 03:57

import clientes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del cliente', max_length=100, validators=[clientes.models.validate_no_special_chars])),
                ('email', models.EmailField(help_text='Correo electrónico del cliente (único)', max_length=254, unique=True, validators=[clientes.models.validate_email])),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del cliente', max_length=20, null=True, validators=[clientes.models.validate_phone_number])),
                ('direccion', models.TextField(blank=True, help_text='Dirección del cliente', null=True, validators=[clientes.models.validate_address])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se registró el cliente')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización del registro')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el cliente está activo')),
                ('tipo_cliente', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('corporativo', 'Corporativo'), ('distribuidor', 'Distribuidor')], default='regular', help_text='Tipo o categoría del cliente', max_length=20)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el cliente', null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del cliente', null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que actualizó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_actualizados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que creó o gestiona este cliente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['email'], name='clientes_cl_email_eae461_idx'), models.Index(fields=['nombre'], name='clientes_cl_nombre_c231de_idx'), models.Index(fields=['-fecha_registro'], name='clientes_cl_fecha_r_483ee3_idx'), models.Index(fields=['is_active'], name='clientes_cl_is_acti_47b92e_idx'), models.Index(fields=['tipo_cliente'], name='clientes_cl_tipo_cl_cae2d6_idx')],
            },
        ),
    ]
